### ISSUE TITLE
好像跟dice的黑名单产生了冲突

### ISSUE THREAD

**Issue by Apurikotto** [mzdluo123/SimpleGroupAuth#3]
![QQ截图20210926232403](https://user-images.githubusercontent.com/72537772/134811914-d6e3fbf7-bbae-46d7-8529-9ec7f7ae569b.jpg)
![QQ截图20210926232500](https://user-images.githubusercontent.com/72537772/134811924-a194a772-20d8-4f41-a742-f5be5798eeae.jpg)
有个新人加了群之后没输入验证码，bot显示是他把bot，t出了，事实上是bot把他t了，不知道是哪里出了问题，有可能是DICE的问题也有可能是验证码插件的问题。。
有点乱因为我自己都睡着了然后被吵醒，如果打扰了真是不好意思。。。

**Comment by Apurikotto** [comment]
顺便一提在群里是这样的
![QQ截图20210926234946](https://user-images.githubusercontent.com/72537772/134812786-dddf2660-2709-4d50-820f-7d9c94251d3c.jpg)

**Comment by mzdluo123** [comment]
这是预期的，没有输入验证码应该被踢出

**Comment by Apurikotto** [comment]
额，我想说的意思是，虽然是没输入验证码被t出了，但是dice端显示的是bot被t出了，是哪里的逻辑出了问题。
可能我自己的逻辑也不好吧，说不清楚，就是A进了群没输入验证码被bot踢了，虽然正常进行了把A踢出去的操作，但是dice这里显示的是A把bot踢了，由此触发了dice的防t人机制，然后bot自动退群了。
就是反应一个逻辑冲突的bug，打扰了
