### ISSUE TITLE
qq官方机器人加群被要求验证造成反复刷屏

### ISSUE THREAD

**Issue by DreamOneX** [mzdluo123/SimpleGroupAuth#5]
![30cfab095b1ac9af_edit_219773048552400](https://user-images.githubusercontent.com/83908457/171642983-a5b58d04-0b85-4e76-91fc-54722971b817.png)
图片如上  
~~虽然问题不大~~
个人想法是判断为官方机器人的qq号自动通过验证

**Comment by mzdluo123** [comment]
那只能列一个官方机器人的白名单出来，你可以pr一下
